version: 2.1
jobs:
  build:
    docker:
      - image: sigtot/ros-melodic-bionic-gtsam:1.0.2
    steps:
      - checkout
      - run: |
          source /opt/ros/melodic/setup.bash
          cd src
          catkin_init_workspace
          cd ..
          bash -c 'catkin_make'
  test:
    docker:
      - image: sigtot/ros-melodic-bionic-gtsam:1.0.2
    steps:
      - checkout
      - run: |
          ldconfig # Needed to find correct gtest libs
          source /opt/ros/melodic/setup.bash
          cd src
          catkin_init_workspace
          cd ..
          bash -c 'roscore & echo waiting for roscore && sleep 3 && catkin_make run_tests && catkin_test_results'
workflows:
  build-and-test:
    jobs:
      - build
      - test
